### ISSUE TITLE
Lumen 5.6.3 won't load config files

### ISSUE THREAD

**Issue by Phil-Barker** [digiaonline/lumen-elasticsearch#104]
### What did you do?
Setup a project with Lumen 5.6.3, was working fine on local development but now need to configure a custom host.

I added the /config/elasticsearch.php but it is not registered
Digging through the lumen documentation it appears that config/*.php files are not supported any more and all config comes from the .env file

### What did you expect to happen?
To be able to add a custom host.

### What actually happened?
The default config was used.

### What versions of PHP, Lumen and this module are you using?
PHP 7.1.17
Lumen 5.6.3

**Comment by Phil-Barker** [comment]
My apologies this seems to have been just a caching issue.

The removal of the information about using laravel config with lumen in the documentation threw me.

**Comment by crisu83** [comment]
No worries @Phil-Barker. It's always nice when people are opening issues on our projects. :D
