### ISSUE TITLE
Count and display items that failed indexing

### ISSUE THREAD

**Issue by wojo1206** [digiaonline/lumen-elasticsearch#111]
### What did you do?
Mass index using IndexCommand
### What did you expect to happen?
Index all items
### What actually happened?
Indexed some items
### What versions of PHP, Lumen and this module are you using?
7.1.20, Lumen 5.6 and this module ^3.3
Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```php

```
Some items were not indexed due to mapping error. Would be nice to catch and display count at the end.

**Comment by Jalle19** [comment]
Does Elasticsearch indicate somehow which items it failed to index? I suspect we ignore some return value somewhere?

**Comment by wojo1206** [comment]
Response from 

```php
// IndexCommand.php
$this->elasticsearchService->bulk($bulkQuery->toArray());
```
provides individuals results. From elastic docs:

`The response to a bulk action is a large JSON structure with the individual results of each action that was performed. The failure of a single action does not affect the remaining actions.`

In this case, aggregating and and nice printing the results would be great.

**Comment by Jalle19** [comment]
@wojo1206 do you know any way to reliably trigger this type of error? It's a bit hard to code support for this blindly, even with the documentation

**Comment by Quantiversal** [comment]
@Jalle19  I'd like to mention the way I got the error was by having an index with a mapping field of type "date", then trying to index a date that did not match the format.

**Comment by Jalle19** [comment]
https://github.com/digiaonline/lumen-elasticsearch/releases/tag/3.5.0
