### ISSUE TITLE
Memory leak during indexing (introduced between 3.1 and 3.5)

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-elasticsearch#120]

**Comment by hugovk** [comment]
Ever used git bisect? It's brilliant for finding regressions.

https://robots.thoughtbot.com/git-bisect

**Comment by Jalle19** [comment]
@hugovk sure, although in this case it was pretty easy to track down without bisecting

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/lumen-elasticsearch#3.5.1
