### ISSUE TITLE
BulkResponseAggregator Undefined index

### ISSUE THREAD

**Issue by JordanBCX** [digiaonline/lumen-elasticsearch#138]
### What did you do?
Attempted to bulk insert indexes.

### What did you expect to happen?
Indexes to be inserted.

### What actually happened?
An error occurred.

```
In BulkResponseAggregator.php line 47:
Undefined index: type  
```

### What versions of PHP, Lumen and this module are you using?
PHP: 7.2.23
Lumen: 5.8.13
Elasticsearch: 7.5.0

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

I was able to fix the error by replacing line 47 with the following two lines.
```php
$item = $item["index"];
$item = $item['_type'];
```

I've tried to force an error to see the response object, but I've been unable to in my short testing time.

With the error object, I can open a PR to fix any potential errors with that.

**Comment by Jalle19** [comment]
I'm afraid this library isn't compatible with Elasticsearch 7.x at the moment. We're still using 5.x in most of ours projects so we haven't bothered making it work with newer versions.

**Comment by Jalle19** [comment]
Can you post a stacktrace and the full error of what's happening? I recently changed this code so maybe I broke it somehow.

**Comment by JordanBCX** [comment]
I'll try and reproduce the error, but IIRC that was the only error since it was part of the bulk migration.

**Comment by Jalle19** [comment]
Crap, looks like I broke this in 3.8.0. I'll push a fix ASAP. Thanks for reporting!

**Comment by Jalle19** [comment]
Fixed in https://packagist.org/packages/nordsoftware/lumen-elasticsearch#3.8.1

**Comment by JordanBCX** [comment]
Thank you @Jalle19
