### ISSUE TITLE
Add authentication to connect with security enabled elasticsearch engine

### ISSUE THREAD

**Issue by outis10** [digiaonline/lumen-elasticsearch#143]
### What did you do?
We need to add authentication to connect to amazon elasticsearch service
### What did you expect to happen?

I expect that when add username and password  parameters to the config/elasticsarch.php file
the  library allow the connection and create index.

### What actually happened?
When run the command: 

`php artisan elastic:index:create config/elasticsearch/segment-index.php`

and get the following error: 
```
In ClientBuilder.php line 162:
                                                 
  Unknown parameters provided: usernamepassword  

```                                                 

we try with user and pass parameter  and get the same results.

### What versions of PHP, Lumen and this module are you using?
Lumen version :6.2
PHP : 7.3
lumen-elasticsarch:3.8.1

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```php
<?php
return [
    /*
    |--------------------------------------------------------------------------
    | Elasticsearch host urls.
    |--------------------------------------------------------------------------
    |
    | Set the hosts to use for connecting to elasticsearch.
    |
    */
    'hosts'        => [env('ELASTICSEARCH_HOST').':'.env('ELASTICSEARCH_PORT')],
     'username'   => env('ELASTICSEARCH_USER', null),
    'password'   => env('ELASTICSEARCH_PASS', null),
 
    /*
     * The prefix to use for index names
     */
    'index_prefix' => env('ELASTICSEARCH_INDEX_PREFIX'),
];

```

**Comment by Jalle19** [comment]
Do you have a link to the AWS documentation for this mode of authentication? I thought only IAM and IP-based authentication was supported?

**Comment by Jalle19** [comment]
If you're using basic authentication you can try to embed the credentials in your hosts line: https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_security.html

**Comment by outis10** [comment]
> If you're using basic authentication you can try to embed the credentials in your hosts line: https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_security.html

These solution  is working in my docker. thanks in advance.
