### ISSUE TITLE
Implement regexp_queries

### ISSUE THREAD

**Issue by michail1982** [digiaonline/lumen-elasticsearch#15]
### What did you do?
Want to use https://www.elastic.co/guide/en/elasticsearch/guide/current/_wildcard_and_regexp_queries.html

### What did you expect to happen?
```php
$queryBuilder->createRegexpQuery()
```
### What actually happened?

Fatal error

### What versions of PHP, Lumen and this module are you using?

PHP 5.6 ; Lumen 5.4

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

**Comment by kryysler** [comment]
Unfortunately we do not have support for Regexp queries at the moment. You're welcome to do a PR for it if you want. We currently have no timeline for adding support for these types of queries.

**Comment by michail1982** [comment]
tnx @kryysler , @Jalle19
