### ISSUE TITLE
Support Elasticsearch 5.x

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-elasticsearch#19]
Ensure that the library works with Elasticsearch 5.x.

**Comment by rtzm** [comment]
I've been having issues with this as well. I can't use the current fieldtypes of `text` or `keyword`, and have to use the deprecated `string` fieldtype for now.

**Comment by crisu83** [comment]
@hungnq1989 will take a look at this when we has time, probably within a month or so.

**Comment by richardsweeney** [comment]
Might i bump this issue? Are there any immediate plans to look into this?

**Comment by Jalle19** [comment]
Plans, yes. Immediate, depends. We haven't needed any 5.x features ourselves so far which is why there hasn't been much progress. I'll see if we can allocate some resources to this sooner.

**Comment by richardsweeney** [comment]
@Jalle19 ok thanks! Actually for us this isn't going to be an issue right now anyway as it turns out :)

Thanks for the library!
