### ISSUE TITLE
Memory issues with PHP

### ISSUE THREAD

**Issue by hungneox** [digiaonline/lumen-elasticsearch#64]
### What did you do?
Run index command with `BULK_SIZE=500`
### What did you expect to happen?

All data should be successfully indexed

### What actually happened?

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 63912944 bytes)
```

**Comment by Jalle19** [comment]
Use a smaller bulk size?

**Comment by hungneox** [comment]
@Jalle19 I know how to fix it :D

**Comment by Jalle19** [comment]
So what's the problem?

**Comment by hungneox** [comment]
@Jalle19  Pls see my PR #65
