### ISSUE TITLE
Use asynchronous request when reindexing

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-elasticsearch#67]
### What did you do?

Reindexed a large index on AWS ES

### What did you expect to happen?

Everything to work

### What actually happened?

AWS is stupid and the timeout for the load balancer that sits in front of ES cannot be configured, so the reindex request fails while the operation completes in the background.

**Comment by hungneox** [comment]
@Jalle19 FYI, I think the problem is not `reindex` itself, because it returns immediately https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_wfc.html#_link_linkend_reindex_reindex_link_2

**Comment by Jalle19** [comment]
@hungneox it definitely doesn't return immediately, at least not with the PHP SDK. We can make ES wait until the request completes, but the load balancer that sits in front of ES cannot be configured to allow for longer timeouts.

**Comment by Jalle19** [comment]
Fixed by https://github.com/digiaonline/lumen-elasticsearch/pull/72
